# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransport.proto\x12\ttransport\"V\n\x0cRouteRequest\x12\x11\n\tstart_lat\x18\x01 \x01(\x01\x12\x11\n\tstart_lng\x18\x02 \x01(\x01\x12\x0f\n\x07\x65nd_lat\x18\x03 \x01(\x01\x12\x0f\n\x07\x65nd_lng\x18\x04 \x01(\x01\"G\n\rRouteResponse\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x16\n\x0etransport_mode\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x01\x32Q\n\x10TransportService\x12=\n\x08GetRoute\x12\x17.transport.RouteRequest\x1a\x18.transport.RouteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUEST']._serialized_start=30
  _globals['_ROUTEREQUEST']._serialized_end=116
  _globals['_ROUTERESPONSE']._serialized_start=118
  _globals['_ROUTERESPONSE']._serialized_end=189
  _globals['_TRANSPORTSERVICE']._serialized_start=191
  _globals['_TRANSPORTSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
